spring:
  config:
    import: aws-secretsmanager:/secrets/postgres
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://springtodo-db.cnkagk22sv6c.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: ${todo-postgres.id}
    password: ${todo-postgres.pw}
    hikari:
      driver-class-name: org.postgresql.Driver