spring:
  application:
    name: todoapp
  profiles:
    active: "dev"
  data:
    rest:
      base-path: api
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${CLIENT_ID_GITHUB}
            clientSecret: ${CLIENT_SECRET_GITHUB}
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
server:
  forward-headers-strategy: NATIVE
